### ISSUE TITLE
Usable with Exponent?

### ISSUE THREAD

**Issue by idibidiart** [charlesvinette/react-native-haptic#1]
Hey, 

So this is amazing!

I'm just coming back to RN after a long time and I find that Exponent is the easiest way to build apps now. I had built my own custom keyboard component back in August of last year but I never figured out how to package it for Exponent, which was very new at the time. 

How would we use this in Exponent?

Thanks!!

**Comment by charlesvinette** [comment]
Hi @idibidiart ! You can install any packages that do NOT interact with native modules. For example, my react-native-haptic package wouldn't work out of the box. However, you can pull Exponent client which is open sourced and then modify it to work with your package.

**Comment by idibidiart** [comment]
Brent Vatne, whom I think is associated with Exponent, has pointed out that there is discussion around allowing developers to work across both XCode and Exponent using the "detach" idea, where a projected would be detached so it's runnable in XCode and can incorporate custom native components like yours (and some of the ones I had written but not released yet) and then put them in conditionals so they're ignored when you go back to Exponent. Seems like a good idea. Here's the link, fyi: https://t.co/Oyt9oEi0wd  ... Closing this and thanks for your answer!
